project:
  name: sample-api
  version: 0.1

server.port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:ccp;DB_CLOSE_ON_EXIT=FALSE
    username: sample-api
    password: sample-api
    driver-class-name: org.h2.Driver
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.H2Dialect